<?php

declare(strict_types=1);

/**
 * This file was generated by glugox/module-generator at 2025-10-24T10:19:01+00:00.
 */

namespace Glugox\Billing\Providers;

use Illuminate\Support\ServiceProvider;

class ModuleServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        // Register module bindings here.
    }

    public function boot(): void
    {
        // Bootstrap any module services.
    }
}
